name = "mta-app"
main = "dist/server/entry.mjs"
compatibility_date = "2024-01-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MtaStateObject"]

[[durable_objects.bindings]]
name = "MTA_STATE"
class_name = "MtaStateObject"
